name: SuperVanish
version: '3.2.3'
main: dev.philippcmd.supervanish.Main
api-version: '1.21'

commands:
  vanish:
    description: vanishes the player
    usage: /vanish
    permission: vanish.use
    permission-message: You do not have permission to run that command

  vanish-show:
    description: shows normal vanished players
    usage: /vanish-show
    permission: vanish.show
    permission-message: You do not have permission to run that command

  vanish-list:
    description: lists all vanished players
    usage: /vanish-list
    permission: vanish.list
    permission-message: You do not have permission to run that command

  supervanish:
    description: supervanishes the player
    usage: /supervanish
    aliases: [sv]
    permission: vanish.supervanish
    permission-message: You do not have permission to run that command

permissions:
  vanish.use:
    description: Allows usage of /vanish
    default: op

  vanish.show:
    description: Allows usage of /vanish-show
    default: op

  vanish.list:
    description: Allows usage of /vanish-list
    default: op

  vanish.supervanish:
    description: Allows usage of /supervanish
    default: op

  vanish.*:
    description: master permission
    children:
      - vanish.use
      - vanish.show
      - vanish.list
      - vanish.supervanish